on:
  push:                 
    branches:           
      - main    
name: Deploy  
jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master        
      - uses: SamKirkland/FTP-Deploy-Action@2.0.0   
        with:                                        
          server: mh.rsw.jp
          username: ${{ secrets.FTP_USERNAME }} 
          password: ${{ secrets.FTP_PASSWORD }} 
          local_dir: ./                          
          remote_dir: /reports.cf
          exclude: |
            **/.git*
            **/.git*/**
            LICENSE
            Plam.md
            README.md
            example.config.php
